### Requête GET pour récupérer tous les animaux
GET http://localhost:3000/api/animal
Accept: application/json

### Requête GET pour récupérer un animal par son ID
GET http://localhost:3000/api/animal/85
Accept: application/json

###
GET http://localhost:3000/api/animal/1000
Accept: application/json

### Requête POST pour créer un nouvel animal pour une association
POST http://localhost:3000/api/animal
Content-Type: application/json

{ 
  "name": "Janine",
  "species": "Panthera leo",
  "breed": "Berger Allemand",
  "gender":"F",
  "age": 5,
  "size":"grand",
  "id_association":1

}

### Requête POST pour créer un nouvel animal avec erreur sur le nom
POST http://localhost:3000/api/animal
Content-Type: application/json

{ 
  "name": 2,
  "species": "Panthera leo",
  "breed": "Berger Allemand",
  "gender":"M",
  "age": 5,
  "size":"grand",
  "id_association":1

}

### Requête POST pour créer un nouvel animal avec erreur
POST http://localhost:3000/api/animal
Content-Type: application/json

{ 
  "name": "janine",
  "species": 56,
  "breed": true,
  "gender":"MFHG",
  "age": "1 an",
  "size":"grand",
  "id_association":765
}

### Requête PATCH pour modifier un animal par son ID
PATCH http://localhost:3000/api/animal/84
Content-Type: application/json

{
  "name": "Lion modifié",
  "age": 6
}

### Requête PATCH pour modifier un animal par son ID
PATCH http://localhost:3000/api/animal/85
Content-Type: application/json

{
  "species": "Chien Chat",
  "breed": "expérience raté",
  "gender": "M",
  "size": "petit"
}

### Requête PATCH pour modifier un animal par son ID avec erreur
PATCH http://localhost:3000/api/animal/85
Content-Type: application/json

{
  "name": 76,
  "species": true,
  "breed": "expérience raté",
  "gender": "Mjh",
  "age": true,
  "size": 65
}

### Requête PATCH pour modifier un animal par son ID sans modif
PATCH http://localhost:3000/api/animal/85
Content-Type: application/json

{
}

### Requête DELETE pour supprimer un animal par son ID
DELETE http://localhost:3000/api/animal/85
Accept: application/json
