### Requête GET pour récupérer tous les animaux
GET http://localhost:3000/api/animal
Accept: application/json

### Requête GET pour récupérer un animal par son ID
GET http://localhost:3000/api/animal/72
Accept: application/json

#-------------Requête POST pour créer un nouvel animal (association)-----

### ! SANS TOKEN
POST http://localhost:3000/api/animal
Content-Type: application/json

{ 
  "name": "Janine",
  "species": "Panthera leo",
  "breed": "Berger Allemand",
  "gender":"F",
  "age": 5,
  "size":"grand",
  "id_association":1

}
###* AVEC TOKEN
POST http://localhost:3000/api/animal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJtYXJpZS5sZWZlYnZyZUBlbWFpbC5jb20iLCJyb2xlIjoiYXNzb2NpYXRpb24iLCJpYXQiOjE3MzEzMzg5MzMsImV4cCI6MTczMTM0MjUzM30.yZ1TAAL5b1bIbylR366vjWGZFU3N3Um74hkL-PycVZQ

{ 
  "name": "Janine",
  "species": "Panthera leo",
  "breed": "Berger Allemand",
  "gender":"F",
  "age": 5,
  "size":"grand"
}

#---------------------pour modifier un animal par son ID (association)--------------------

###! SANS TOKEN
PATCH http://localhost:3000/api/animal/85
Authorization: Bearer 
Content-Type: application/json

{
  "species": "Chat Chien",
  "breed": "expérience raté",
  "gender": "M",
  "size": "petit"
}

###* AVEC TOKEN
PATCH http://localhost:3000/api/animal/88
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzEzMzg4MjYsImV4cCI6MTczMTM0MjQyNn0.imn-Ki32lt2Slx8dqMbr-E_pEtmwuhT85YD61OU59Nc
Content-Type: application/json

{
  "species": "Chat Chien",
  "breed": "expérience raté",
  "gender": "F",
  "size": "petit"
}


#------------Pour supprimer un animal par son ID (association)-----------


###! SANS TOKEN
DELETE http://localhost:3000/api/animal/115
Accept: application/json


###* AVEC TOKEN

DELETE http://localhost:3000/api/animal/87
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJwaWVycmUuZHVib2lzQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTMzODg1MiwiZXhwIjoxNzMxMzQyNDUyfQ.VPbjuZnf-6sSzv12mP-Mc-NMmteFVRIJYRF1Kce1u2s