### Lister toutes les demandes
GET http://localhost:3000/api/ask


### Obtenir le détail d'une demande
GET http://localhost:3000/api/ask/1


### Créer une nouvelle demande
POST http://localhost:3000/api/ask
Content-Type: application/json

{
  "id_family": 1,
  "id_animal": 10
}


### Modifier une demande
PATCH http://localhost:3000/api/ask/1
Content-Type: application/json

{
  "status": "en cours"
}
