### Requête GET pour récupérer toutes les associations
GET http://localhost:3000/api/association
Accept: application/json

### Requête GET pour récupérer toutes les associations avec erreur
GET http://localhost:3000/api/associations
Accept: application/json

### Requête GET pour récupérer une association par son ID
GET http://localhost:3000/api/association/10
Accept: application/json

### Requête GET pour récupérer une association par son ID avec erreur
GET http://localhost:3000/api/association/1000
Accept: application/json

### Requête patch pour modifier une asso
PATCH http://localhost:3000/api/association/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDUsImVtYWlsIjoiYXNzb2NpYXRpb24xNEBleGVtcGxlLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTA2ODM2MywiZXhwIjoxNzMxMDcxOTYzfQ.Ol07BoAFETz7jML9YpVr1wLcfONdHbQ7jyMCaNSiCYc
Content-Type: application/json

{
    "representative": "La fete du chat",
    "address": "rue du gros minet"
}

### Requête patch pour modifier une asso et son user
PATCH http://localhost:3000/api/association/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJwaWVycmUuZHVib2lzQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTMzODg1MiwiZXhwIjoxNzMxMzQyNDUyfQ.VPbjuZnf-6sSzv12mP-Mc-NMmteFVRIJYRF1Kce1u2s
Content-Type: application/json

{
    "representative": "La fete des animaux",
    "address": "rue des boules de poils",
    "user": {
        "firstname": "Chapi",
        "password": "j'aimelesanimaux2020"
    }
}

### Requête patch pour modifier un user sans son asso
PATCH http://localhost:3000/api/association/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJwaWVycmUuZHVib2lzQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTMzODg1MiwiZXhwIjoxNzMxMzQyNDUyfQ.VPbjuZnf-6sSzv12mP-Mc-NMmteFVRIJYRF1Kce1u2s
Content-Type: application/json

{
    "user": {
        "firstname": "Chapi Chapi",
        "lastname": "CHAPO"
    }
}

### Requête patch pour modifier une asso et son user avec erreur
PATCH http://localhost:3000/api/association/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzEzMzg4MjYsImV4cCI6MTczMTM0MjQyNn0.imn-Ki32lt2Slx8dqMbr-E_pEtmwuhT85YD61OU59Nc

Content-Type: application/json

{
    "representative": "la maison des animaux",
    "address": "rue des boules de poils",
    "user": {
        "firstname": "Chapi",
        "password": 9
    }
}