### Requête GET pour récupérer toutes les familles
GET http://localhost:3000/api/family
Accept: application/json

### Requête GET pour récupérer toutes les familles avec erreur
GET http://localhost:3000/api/familly
Accept: application/json

### Requête GET pour récupérer une famille par son ID
GET http://localhost:3000/api/family/10
Accept: application/json

### Requête GET pour récupérer une famille par son ID avec erreur
GET http://localhost:3000/api/family/1000
Accept: application/json

### Requête GET pour récupérer une famille par son ID en string
GET http://localhost:3000/api/family/famille
Accept: application/json
