### ---------Récupérer toutes les familles-(admin asso)--------------
#! SANS TOKEN
GET http://localhost:3000/api/family
Accept: application/json


###* AVEC TOKEN
GET http://localhost:3000/api/family
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJhbGljZS5iZXJuYXJkQGVtYWlsLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTM0MzA5OCwiZXhwIjoxNzMxMzQ2Njk4fQ.xmxDXR6SJ3xaOJSNOteEaOk6xtL0gFzVv7czCVxBTas
Accept: application/json

#----------------Récupérer une famille par son ID (admin asso)----------------

###! SANS TOKEN
GET http://localhost:3000/api/family/1
Accept: application/json


### AVEC TOKEN
GET http://localhost:3000/api/family/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzEzMzg4MjYsImV4cCI6MTczMTM0MjQyNn0.imn-Ki32lt2Slx8dqMbr-E_pEtmwuhT85YD61OU59Nc
Accept: application/json

### modification d'une family
PATCH http://localhost:3000/api/family/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZWFuLmR1cG9udEBlbWFpbC5jb20iLCJyb2xlIjoiZmFtaWx5IiwiaWF0IjoxNzMxMzM4NjgzLCJleHAiOjE3MzEzNDIyODN9.2b5rzZeJwTkePzXopfkcNssBcHDEgYfMrnF-sG5Am0w
Content-Type: application/json

{
    "address": "rue de Gisors POOOues",
    "user": {
        "firstname": "Charles",
        "password": "CoucouToi383!"
    }
}

### Suppression d'une family
DELETE http://localhost:3000/api/family/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzb3BoaWUubWFydGluQGVtYWlsLmNvbSIsInJvbGUiOiJmYW1pbHkiLCJpYXQiOjE3MzEzMzg4MjYsImV4cCI6MTczMTM0MjQyNn0.imn-Ki32lt2Slx8dqMbr-E_pEtmwuhT85YD61OU59Nc
Content-Type: application/json