### Visulaiser tous les utilisateurs
GET http://localhost:3000/api/user
Content-Type: application/json

### Visulaiser un utilisateur
GET http://localhost:3000/api/user/20
Content-Type: application/json

### Visulaiser un utilisateur qui n'existe pas
GET http://localhost:3000/api/user/1000
Content-Type: application/json

### Requête pour tester l'inscription  pour un utilisateur de type "family"
POST http://localhost:3000/api/user 
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "FAmilyTest",
  "email": "testFamqsilyd17@example.com",
  "password": "Family@123",
  "family":{
    "address": "123 Main St",
    "postal_code": "12345",
    "city": "Paris",
    "phone": "0123456789"
  }
}

### Requête pour tester l'inscription pour un utilisateur de type "association"
POST http://localhost:3000/api/user 
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "asso",
  "email": "association15@exemple.com",
  "password": "Association1990*",
  "association":{
    "address": "123 Main St",
    "postal_code": "12345",
    "city": "Paris",
    "phone": "0123456789",
    "rna_number": "W100000003",
    "representative": "asso"
  }

}

# Toker famille eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImVtYWlsIjoidGVzdEZhbWlseWQyQGV4YW1wbGUuY29tIiwicm9sZSI6ImZhbWlseSIsImlhdCI6MTczMDk4MzE0NywiZXhwIjoxNzMwOTg2NzQ3fQ.0EEraE-Y-OnGXOtfj_2gdgcMNA0ZzJcJhH4wWDgEcTk
# Token association eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiYXNzbzkxMTUyNTVAc3hhc21wbGUuY29tIiwicm9sZSI6ImFzc29jaWF0aW9uIiwiaWF0IjoxNzMwOTgzMjA3LCJleHAiOjE3MzA5ODY4MDd9.2mSVcFkl85pRXg_GhaubUtQ5KDsnY0k3irHOKFOry_o
### Visualiser tous les utilisateurs
GET http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiYXNzbzkxMTUyNTVAc3hhc21wbGUuY29tIiwicm9sZSI6ImFzc29jaWF0aW9uIiwiaWF0IjoxNzMwOTgzMjA3LCJleHAiOjE3MzA5ODY4MDd9.2mSVcFkl85pRXg_GhaubUtQ5KDsnY0k3irHOKFOry_o


#------------------Supprimer un utilisateur (asso, family admin)------------------

###! SANS TOKEN
DELETE http://localhost:3000/api/user/27
Authorization: Bearer 
Accept: application/json


###* AVEC TOKEN
DELETE http://localhost:3000/api/user/30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiYXNzbzkxMTUyNTVAc3hhc21wbGUuY29tIiwicm9sZSI6ImFzc29jaWF0aW9uIiwiaWF0IjoxNzMwOTgzMjA3LCJleHAiOjE3MzA5ODY4MDd9.2mSVcFkl85pRXg_GhaubUtQ5KDsnY0k3irHOKFOry_o
Accept: application/json


#------------------Modifier un utilisateur (asso family)---------------------

###! SANS TOKEN
PATCH http://localhost:3000/api/user/34
Content-Type: application/json

{
  "firstname": "Jean",
  "email": "jeandupont@email.com",
  "password": "password",
  "family": {
    "postal_code": "27630"
  }
}

### Modifier une association
PATCH http://localhost:3000/api/user/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImVtYWlsIjoiYXNzb2NpYXRpb24xM0BleGVtcGxlLmNvbSIsInJvbGUiOiJhc3NvY2lhdGlvbiIsImlhdCI6MTczMTA1NTI1NSwiZXhwIjoxNzMxMDU4ODU1fQ.qDgwKguiVn2nWcqOoz6mLctgAApGAq0auhX5GBJkOFI

{
  "association": {
    "address": "rue des Quesadillas en folie de fou"
  }
}

###* AVEC TOKEN
PATCH http://localhost:3000/api/user/43
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImVtYWlsIjoidGVzdEZhbXFzaWx5ZDEzQGV4YW1wbGUuY29tIiwicm9sZSI6ImZhbWlseSIsImlhdCI6MTczMTA2MjM1MCwiZXhwIjoxNzMxMDY1OTUwfQ.Yj-hfePdusMmCHFja3c83nx4tu8JbpJ8lTne547nOLU

{
  "firstname": "Jea",
  "email": "jeandupont@email.com",
  "password": "password",
  "family": {
    "address": "rue des Quesadillas en folie"
  }
}

###* AVEC TOKEN
PATCH http://localhost:3000/api/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsImVtYWlsIjoidGVzdEZhbXFzaWx5ZDJAZXhhbXBsZS5jb20iLCJyb2xlIjoiZmFtaWx5IiwiaWF0IjoxNzMxMDU1MzA5LCJleHAiOjE3MzEwNTg5MDl9.KJkzhdIJW_sbf_Fm2envqxrP_GeG8P4LcERjDBJF7Tw

{
  "firstname": "Jean",
  "email": "jeandupont@email.com",
  "password": "password",
  "family": {
    "address": "rue des Quesadillas en folie"
  }
}
#---------------------------------------------
