DROP TABLE IF EXISTS animal;
DROP TABLE IF EXISTS association;
DROP TABLE IF EXISTS family;
DROP TABLE IF EXISTS "user";  
DROP TABLE IF EXISTS ask;

CREATE TABLE "user" (  -- Utilisation de guillemets sinon conflit avec mots réservés dans postgres à discuter ensemble si modification
  id           INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT,
  lastname    VARCHAR(50) NOT NULL,
  firstname   VARCHAR(50) NOT NULL,
  email        VARCHAR(100) NOT NULL,
  password     VARCHAR(255) NOT NULL,
  role         VARCHAR(20),
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE family (
  id                 INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT,
  address            VARCHAR(255) NOT NULL,
  phone              VARCHAR(15) NOT NULL,
  number_of_children INT,
  number_of_animals  INT,
  garden             BOOLEAN NOT NULL,
  description        TEXT,
  profile_photo      VARCHAR(255),
  id_user            ENTITY FOREIGN KEY NOT NULL UNIQUE,  -- clé étrangère vers USER (ASSOCIER)
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE association (
  id                 INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT,
  rna_number         VARCHAR(42) UNIQUE NOT NULL
  representative     VARCHAR(100) NOT NULL,
  address            VARCHAR(255) NOT NULL,
  phone              VARCHAR(15) NOT NULL,
  description        TEXT NULL,
  status             VARCHAR(15) NOT NULL,
  profile_photo      VARCHAR(255),
  id_user         ENTITY FOREIGN KEY NOT NULL UNIQUE,  -- clé étrangère vers USER (DEFINIR)
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE animal (
  id               INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT,
  name             VARCHAR(50) NOT NULL,
  species          VARCHAR(30) NOT NULL,
  breed            VARCHAR(50) NOT NULL,
  gender           CHAR(1) NOT NULL,
  age              INT NOT NULL,
  size             VARCHAR(30) NOT NULL,
  description      TEXT,
  profile_photo    VARCHAR(255),
  photo1           VARCHAR(255),
  photo2           VARCHAR(255),
  photo3           VARCHAR(255),
  id_family        ENTITY FOREIGN KEY NULL,      -- clé étrangère vers FAMILY (HEBERGER)
  id_association   ENTITY FOREIGN KEY NOT NULL,  -- clé étrangère vers ASSOCIATION (DETENIR)
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

CREATE TABLE ask (
  id_family  INT PRIMARY KEY FOREIGN KEY NOT NULL,
  id_animal  INT PRIMARY KEY FOREIGN KEY NOT NULL,
  status       VARCHAR(15) NOT NULL,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

-- Fonction pour mettre à jour le timestamp
CREATE OR REPLACE FUNCTION update_timestamp() 
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;





-- Triggers pour mettre à jour les timestamps
-- Création d'un trigger nommé 'update_animal_timestamp'
CREATE TRIGGER update_animal_timestamp
    -- Le trigger se déclenche avant chaque mise à jour de la table 'animal'
    BEFORE UPDATE ON animal
    -- Pour chaque ligne modifiée dans la table 'animal', exécute la fonction suivante
    FOR EACH ROW 
    -- Appelle la fonction 'update_timestamp' qui met à jour le champ 'updated_at'
    EXECUTE FUNCTION update_timestamp();


CREATE TRIGGER update_association_timestamp
BEFORE UPDATE ON association
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER update_family_timestamp
BEFORE UPDATE ON family
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER update_user_timestamp
BEFORE UPDATE ON "user"
FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER update_ask_timestamp
BEFORE UPDATE ON ask
FOR EACH ROW EXECUTE FUNCTION update_timestamp();
